@startuml

box "Beam" #e6fcc1
participant "Beam Motor Sub-system" as BeamMotorSubsystem
participant "Beam Main System" as Beam
end box

Beam -> BeamMotorSubsystem: Set Initial Goal (Right Limit)

    loop Continuous Movement
        BeamMotorSubsystem -> BeamMotorSubsystem: Move towards goal

        alt Have stop release
           alt At goal
            alt At left limit
                BeamMotorSubsystem -> BeamMotorSubsystem: Set goal to right limit
            else At right limit
                BeamMotorSubsystem -> BeamMotorSubsystem: Set goal to left limit
            end
           else Moving towards goal

            end
          else Have stop request
                alt At goal
                    BeamMotorSubsystem -> BeamMotorSubsystem: Stop
                else Have stop release
                    BeamMotorSubsystem -> BeamMotorSubsystem: Set goal to previous limit
                end
        end
    end
@enduml