@startuml

box "Male I" #c6eafa
participant "Male System I" as MaleSystemI
end box

box "Beam" #e6fcc1
participant "Beam Motor Sub-system" as BeamMotorSubsystem
participant "Beam Main System" as Beam
end box

box "Male II" #c6eafa
participant "Male System II" as MaleSystemII
end box

' Initialization at boot
Beam -> BeamMotorSubsystem: Set initial goal (right limit)

' Continuous Drive Increment and Drive State Determination by Male Drive Sub-system
par
    loop Continuous Drive Evaluation 

        ' Receive Male System Drive Values
        MaleSystemI -> Beam : Drive I
        MaleSystemII -> Beam : Drive II
        MaleSystemI -> Beam : Motion Request I Stop/Release
        MaleSystemII -> Beam : Motion Request II Stop/Release

        alt Drive I >= Drive II
            Beam -> Beam : Display Dominant Drive I
            alt Motion Request I Stop
                Beam -> BeamMotorSubsystem: Motion Request I Stop
            else Motion Request I Release
                Beam -> BeamMotorSubsystem: Motion Request I Release
            end
        else Drive I < Drive II
            Beam -> Beam : Display Dominant Drive II
            alt Motion Request II Stop
                Beam -> BeamMotorSubsystem: Motion Request II Stop
            else Motion Request II Release
                Beam -> BeamMotorSubsystem: Motion Request II Release
            end 
        end
    end

    loop Continuous Movement

        alt Motion Request Stop
            alt Motion Request I Stop
                alt goal is not reinforcement position I
                    BeamMotorSubsystem -> BeamMotorSubsystem: Set goal to closest reinforcement position I
                else goal is reinforcement position I
                    alt At goal reinforcement Position I
                        BeamMotorSubsystem -> BeamMotorSubsystem: Stop
                    end
                end
            else Motion Request II Stop 
                alt goal is not reinforcement position II
                    BeamMotorSubsystem -> BeamMotorSubsystem: Set goal to closest reinforcement position II
                else goal is reinforcement position II
                    alt At goal reinforcement Position II
                        BeamMotorSubsystem -> BeamMotorSubsystem: Stop
                    end
                end
            end
       BeamMotorSubsystem -> BeamMotorSubsystem: Move towards reinforcement position goal
        else Motion Request Release
            alt At oscillation goal left limit
                BeamMotorSubsystem -> BeamMotorSubsystem: Set oscillation goal to right limit
            else At oscillation goal right limit
                BeamMotorSubsystem -> BeamMotorSubsystem: Set oscillation goal to left limit
            else Not at Goal

            end
       BeamMotorSubsystem -> BeamMotorSubsystem: Move towards oscillation goal
        end
 
        BeamMotorSubsystem -> BeamMotorSubsystem: Determine closest reinforcement position I
        BeamMotorSubsystem -> BeamMotorSubsystem: Determine closest reinforcement position II
    end
end
@enduml