@startuml

participant "Female Horizontal Control Sub-system" as FemaleHorizontalControlSubsystem
participant "Female Vertical Reflector Sub-system" as FemaleVerticalReflectorSubsystem
participant "Female Drive Sub-system" as FemaleDriveSubsystem
'participant "Female System" as FemaleSystem
actor FemaleSystem
participant Environment

' Continuous Drive Increment and Drive State Determination by Female Drive Sub-system
par
    loop Continuous Drive Management
        FemaleDriveSubsystem -> FemaleDriveSubsystem : Increment Drive
        alt drive < lower limit
            FemaleDriveSubsystem -> FemaleSystem : Drive State = Satisfied and Indifferent
        else
            FemaleDriveSubsystem -> FemaleSystem : Drive State = Satisfaction Search
        end
    end

    ' Agent's behavior based on state managed by Female System
    loop Continuous Female System Behavior Management
        alt Female System State = Satisfaction Search
            FemaleSystem -> FemaleHorizontalControlSubsystem : Search
            FemaleSystem -> FemaleVerticalReflectorSubsystem : Stop
            FemaleSystem -> FemaleSystem : Watch for Intermittent Signal
            alt Sense Intermittent Signal
                FemaleSystem -> Environment : Respond (Identifying Sound)
                FemaleSystem -> FemaleHorizontalControlSubsystem : Stop
                FemaleSystem -> FemaleVerticalReflectorSubsystem : Search
                loop Engaging Partner
                    FemaleSystem -> FemaleSystem : Listen for Reinforcement Signal
                    alt Reinforcement Signal
                        FemaleSystem -> FemaleDriveSubsystem : Decrement Drive
                        FemaleDriveSubsystem -> FemaleSystem : Evaluate Drive State
                        alt Drive State = Satisfied and Indifferent
                            FemaleSystem -> FemaleSystem : Satisfaction Display
                            FemaleSystem -> FemaleSystem : State = Satisfied and Indifferent
                        else Drive State = Satisfaction Search
                            FemaleSystem -> FemaleSystem : Continue Engaging Partner
                        end
                    else Timeout
                        FemaleSystem -> FemaleSystem : State = Satisfaction Search
                    end
                end
            else Timeout
                FemaleSystem -> FemaleSystem : State = Satisfaction Search
            end
        else Female System State = Satisfied and Indifferent
            FemaleSystem -> FemaleHorizontalControlSubsystem : Stop
            FemaleSystem -> FemaleVerticalReflectorSubsystem : Stop
        end
    end
end
@enduml