@startuml

start
:Increment O Drive and P Drive;
if (O drive < lower limit AND P drive < lower limit) then (yes)
  :satisfied and indifferent;
else (no)
  if (O drive > upper limit AND P drive > upper limit) then (yes)
    :either O or P satisfaction search;
  else (no)
    if (O drive > lower limit AND O drive > P drive) then (yes)
      :O satisfaction search;
    else (no)
      if (P drive > lower limit AND P drive > O drive) then (yes)
        :P satisfaction search;
      else (no)
        if (O drive == P drive) then (yes)
          :either O or P satisfaction search;
        else (no)
          :ERROR;
        endif
      endif
    endif
  endif
endif
:Loop Back;
stop

@enduml