@startuml

box "Male" #c6eafa
participant "Main System" as MaleMainSystem
end box

box "Male Horizontal Subsystem" #edf8fe
participant "Horizontal Subsystem" as HorizontalSubsystem
end box

MaleMainSystem --> HorizontalSubsystem: transmit motion request

loop Continuous Movement

    alt Motion Request Stop
        alt Goal is not reinforcement position
            HorizontalSubsystem -> HorizontalSubsystem: Set goal to reinforcement position
        else Goal is reinforcement position
            ' continue moving toward reinforcement position
            alt at goal reinforcement position
                HorizontalSubsystem -> HorizontalSubsystem: Stop
            end
        end
        HorizontalSubsystem -> HorizontalSubsystem: Move toward reinforcement position goal

    else Motion Request Release
        alt At oscillation goal left limit
            HorizontalSubsystem -> HorizontalSubsystem: Set oscillation goal to right limit
        else At oscillation goal right limit
            HorizontalSubsystem -> HorizontalSubsystem: Set oscillation goal to left limit
        else Not at oscillation goal
        end
        HorizontalSubsystem -> HorizontalSubsystem: Move towards oscillation goal
    end

end

@enduml