@startuml

title Male Horizontal Sub-system

top to bottom direction

state "Move to Goal" as MoveToGoal
state "Update Goal" as UpdateGoal

note right of UpdateGoal
  Possible Goals:
  - Goal 1: Left Position
  - Goal 2: Right Position
  - Goal 3: Reinforcement Position
end note

[*] --> MoveToGoal : Start

MoveToGoal --> MoveToGoal : Not at Goal
MoveToGoal --> UpdateGoal : At Goal
MoveToGoal --> UpdateGoal : Stop Signal
UpdateGoal --> MoveToGoal : New Goal

@enduml