@startuml
title Female Behavior

state "Satisfied and Inert" as SatisfiedAndInert
state "Satisfaction Search" as SatisfactionSearch
state "Engaging Partner" as EngagingPartner

[*] --> SatisfiedAndInert : Start

SatisfiedAndInert --> SatisfactionSearch : Unsatisfied
SatisfiedAndInert --> SatisfiedAndInert : Satisfied

SatisfactionSearch --> EngagingPartner : Partner Found
SatisfactionSearch --> SatisfactionSearch : No Partner Found

EngagingPartner --> SatisfactionSearch : Partner Lost
EngagingPartner --> EngagingPartner : Unsatisfied
EngagingPartner --> SatisfiedAndInert : Satisfied

@enduml