@startuml
actor Agent
participant DriveManager
participant BehaviorManager
participant Environment
participant Drive

' Continuous Drive Increment and Drive State Determination by DriveManager
par
    loop Continuous Drive Management
        DriveManager -> Drive : Increment
        DriveManager -> Drive : Get O and P Values
        DriveManager -> DriveManager : Determine Drive State
        alt DriveState.SATISFIED_AND_INDIFFERENT
            DriveManager -> BehaviorManager : State = Satisfied
        else DriveState.SATISFACTION_SEARCH
            DriveManager -> BehaviorManager : State = Unsatisfied
        end
    end

    ' Agent's behavior based on state managed by BehaviorManager
    loop Agent's Behavior Management
        alt Unsatisfied
            BehaviorManager -> Environment : Find Partner Request
            Environment -> BehaviorManager : Response (Partner Found/Not Found)
            alt Partner Found
                BehaviorManager -> Environment : Engage Partner
                Environment -> BehaviorManager : Response (Successful/Unsuccessful)
                alt Successful Engagement
                    BehaviorManager -> Drive : Decrement
                else Unsuccessful Engagement
                    BehaviorManager -> BehaviorManager : Resume Searching
                end
            else No Partner Found
                BehaviorManager -> BehaviorManager : Continue Searching
            end
        else Satisfied
            BehaviorManager -> BehaviorManager : Remain Satisfied
        end
    end
end
@enduml