@startuml
title Male Horizontal Sub-system

top to bottom direction

state "Stopped" as Stopped
state "Move Left" as MoveLeft
state "Move Right" as MoveRight

[*] --> Stopped : Boot with Stop Instruction

Stopped --> MoveLeft : No Stop Instruction

MoveLeft --> MoveLeft : No Stop Instruction
MoveLeft --> MoveRight : Left Limit Reached

MoveRight --> MoveRight : No Stop Instruction
MoveRight --> MoveLeft : Right Limit Reached

MoveLeft --> Stopped : Stop Instruction
MoveRight --> Stopped : Stop Instruction
@enduml